name: unet
type: diffusion_lab.models.diffusion.UNet
params:
  base_channels: 64 #64
  image_size: 64 #128
  in_channels: 3
  num_groups: 32
  time_embedding_factor: 4
  num_att_heads: 4
  num_layers: 2
  time_emb_channels: 256