defaults:
  - optimizer: adam
  - loader: default

name: unconditional
run_name: run-0
params:
  timesteps: 1_000
  epochs: 500
  bach_size: 12
  device: mps
  # Additional
  do-ImportanceSampling: false
  n_warmup_rounds: 5
  history_size: 10
  temperature: 5
  do-GradientAccumulation: false
  accum_steps: 1
  # Dataset & Dataloader
  dataset: ${hydra:runtime.cwd}/data/diffusion_training.csv
  # Additional info, model saving/loading
  save_path: ${hydra:runtime.output_dir}/steps
  artifact_path: ${hydra:runtime.output_dir}/artifacts
  model_name: uncond_unet
  load_path: outputs/steps
  load_timestep: 0
  log_step: 1
  save_step: 10
