defaults:
  - optimizer: adam

name: unconditional
run_name: run-0
params:
  timesteps: 1_000
  epochs: 1_000
  bach_size: 16
  device: mps
  dataset: ${hydra:runtime.cwd}/data/diffusion_training.csv
  num_workers: 2
  model_path: ${hydra:runtime.output_dir}/steps
  model_name: model.pth
  log_step: 50
  save_step: 100
