defaults:
  - model: unet
  - schedule: linear
  - train: unconditional
  - tests: unconditional
  - _self_
  - override hydra/job_logging: custom

project:
  name: unconditional-diffusion

train:
  params:
    dataset: ${hydra:runtime.cwd}/data/flower_training.csv

tests:
  params:
    model_abs_path: /Volumes/Filip'sTech/outputs/2025-05-15/23-56-58/steps/step-1000.pth
    test_img_path: data/flower-mini/74/image_01181_jpg.rf.05fa484251c694634a0fd1e94c5c4939.jpg
    test_output_path: ${hydra:runtime.output_dir}/results/
    n_images: 2
    frame_step: 1
    seed: 205

run:
  device: mps
  timesteps: 1_000
  img_size: 64
