defaults:
  - model: unet
  - schedule: cosine
  - train: unconditional
  - tests: unconditional
  - _self_
  - override hydra/job_logging: custom

project:
  name: unconditional-diffusion

train:
  params:
    dataset: ${hydra:runtime.cwd}/data/flower_training.csv

tests:
  params:
    model_abs_path: /Volumes/Filip'sTech/outputs/2025-05-14/17-54-53/steps/step-400.pth
    test_img_path: data/flower-mini/74/image_01181_jpg.rf.05fa484251c694634a0fd1e94c5c4939.jpg

run:
  device: mps
  timesteps: 1_000
  img_size: 64
