defaults:
  - model: unet
  - schedule: cosine
  - train: unconditional
  - tests: unconditional
  - _self_
  - override hydra/job_logging: custom

project:
  name: unconditional-diffusion

run:
  device: mps
  timesteps: 1_000
  img_size: 64
